version: '3'
services:

  python:
    build: ./vote
    container_name: py-vote-app
    depends_on:
      - redis
    ports:
      - "8080:8080"
    networks:
      - voteNetwork

  dotnet:
    build: ./worker
    container_name: worker
    depends_on:
      - redis
      - postgres
    networks:
      - workerNetwork
    
  node:
    build: ./result
    container_name: node-result-app
    depends_on:
      - postgres
    ports:
      - "8081:8888"
    networks:
      - resultNetwork

  redis:
    image: redis:latest
    container_name: redis
    networks:
      - voteNetwork
      - workerNetwork

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: votes
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - resultNetwork
      - workerNetwork

networks:
  voteNetwork:
  resultNetwork:
  workerNetwork:

volumes:
  pgdata:
